/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/


// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "github.com/zhanglianx111/nfs-controller/pkg/apis/nfscontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)


// FakeNFSs implements NFSInterface
type FakeNFSs struct {
	Fake *FakeNfs-controllerV1alpha1
}

var nfssResource = schema.GroupVersionResource{Group: "nfs-controller.yonghui.cn", Version: "v1alpha1", Resource: "nfss"}

var nfssKind = schema.GroupVersionKind{Group: "nfs-controller.yonghui.cn", Version: "v1alpha1", Kind: "NFS"}

// Get takes name of the nFS, and returns the corresponding nFS object, and an error if there is any.
func (c *FakeNFSs) Get(name string, options v1.GetOptions) (result *v1alpha1.NFS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(nfssResource, name), &v1alpha1.NFS{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NFS), err
}

// List takes label and field selectors, and returns the list of NFSs that match those selectors.
func (c *FakeNFSs) List(opts v1.ListOptions) (result *v1alpha1.NFSList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(nfssResource, nfssKind, opts), &v1alpha1.NFSList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NFSList{ListMeta: obj.(*v1alpha1.NFSList).ListMeta}
	for _, item := range obj.(*v1alpha1.NFSList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nFSs.
func (c *FakeNFSs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(nfssResource, opts))
}

// Create takes the representation of a nFS and creates it.  Returns the server's representation of the nFS, and an error, if there is any.
func (c *FakeNFSs) Create(nFS *v1alpha1.NFS) (result *v1alpha1.NFS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(nfssResource, nFS), &v1alpha1.NFS{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NFS), err
}

// Update takes the representation of a nFS and updates it. Returns the server's representation of the nFS, and an error, if there is any.
func (c *FakeNFSs) Update(nFS *v1alpha1.NFS) (result *v1alpha1.NFS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(nfssResource, nFS), &v1alpha1.NFS{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NFS), err
}

// Delete takes name of the nFS and deletes it. Returns an error if one occurs.
func (c *FakeNFSs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(nfssResource, name), &v1alpha1.NFS{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNFSs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(nfssResource, listOptions)
	
	_, err := c.Fake.Invokes(action, &v1alpha1.NFSList{})
	return err
}

// Patch applies the patch and returns the patched nFS.
func (c *FakeNFSs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NFS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(nfssResource, name, data, subresources...), &v1alpha1.NFS{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NFS), err
}
