/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/zhanglianx111/nfscontroller/pkg/apis/nfscontroller/v1alpha1"
	scheme "github.com/zhanglianx111/nfscontroller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NfsesGetter has a method to return a NfsInterface.
// A group's client should implement this interface.
type NfsesGetter interface {
	Nfses(namespace string) NfsInterface
}

// NfsInterface has methods to work with Nfs resources.
type NfsInterface interface {
	Create(*v1alpha1.Nfs) (*v1alpha1.Nfs, error)
	Update(*v1alpha1.Nfs) (*v1alpha1.Nfs, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Nfs, error)
	List(opts v1.ListOptions) (*v1alpha1.NfsList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Nfs, err error)
	NfsExpansion
}

// nfses implements NfsInterface
type nfses struct {
	client rest.Interface
	ns     string
}

// newNfses returns a Nfses
func newNfses(c *NfscontrollerV1alpha1Client, namespace string) *nfses {
	return &nfses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the nfs, and returns the corresponding nfs object, and an error if there is any.
func (c *nfses) Get(name string, options v1.GetOptions) (result *v1alpha1.Nfs, err error) {
	result = &v1alpha1.Nfs{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nfses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Nfses that match those selectors.
func (c *nfses) List(opts v1.ListOptions) (result *v1alpha1.NfsList, err error) {
	result = &v1alpha1.NfsList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("nfses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested nfses.
func (c *nfses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("nfses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a nfs and creates it.  Returns the server's representation of the nfs, and an error, if there is any.
func (c *nfses) Create(nfs *v1alpha1.Nfs) (result *v1alpha1.Nfs, err error) {
	result = &v1alpha1.Nfs{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("nfses").
		Body(nfs).
		Do().
		Into(result)
	return
}

// Update takes the representation of a nfs and updates it. Returns the server's representation of the nfs, and an error, if there is any.
func (c *nfses) Update(nfs *v1alpha1.Nfs) (result *v1alpha1.Nfs, err error) {
	result = &v1alpha1.Nfs{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("nfses").
		Name(nfs.Name).
		Body(nfs).
		Do().
		Into(result)
	return
}

// Delete takes name of the nfs and deletes it. Returns an error if one occurs.
func (c *nfses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nfses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *nfses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("nfses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched nfs.
func (c *nfses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Nfs, err error) {
	result = &v1alpha1.Nfs{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("nfses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
